
package com.gmail.at.sichyuriyy.lab7.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MovieWS", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MovieWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.gmail.at.sichyuriyy.lab7.wsclient.Movie>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllMovies", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllMovies")
    @ResponseWrapper(localName = "getAllMoviesResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllMoviesResponse")
    public List<Movie> getAllMovies();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.gmail.at.sichyuriyy.lab7.wsclient.Movie
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMovieById", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetMovieById")
    @ResponseWrapper(localName = "getMovieByIdResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetMovieByIdResponse")
    public Movie getMovieById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createMovie", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.CreateMovie")
    @ResponseWrapper(localName = "createMovieResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.CreateMovieResponse")
    public void createMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMovie", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteMovie")
    @ResponseWrapper(localName = "deleteMovieResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteMovieResponse")
    public void deleteMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateMovie", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateMovie")
    @ResponseWrapper(localName = "updateMovieResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateMovieResponse")
    public void updateMovie(
        @WebParam(name = "arg0", targetNamespace = "")
        Movie arg0);

}
