
package com.gmail.at.sichyuriyy.lab7.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProducerWS", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProducerWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.gmail.at.sichyuriyy.lab7.wsclient.Producer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducerById", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetProducerById")
    @ResponseWrapper(localName = "getProducerByIdResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetProducerByIdResponse")
    public Producer getProducerById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateProducer", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateProducer")
    @ResponseWrapper(localName = "updateProducerResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateProducerResponse")
    public void updateProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        Producer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProducer", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteProducer")
    @ResponseWrapper(localName = "deleteProducerResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteProducerResponse")
    public void deleteProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createProducer", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.CreateProducer")
    @ResponseWrapper(localName = "createProducerResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.CreateProducerResponse")
    public void createProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        Producer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.gmail.at.sichyuriyy.lab7.wsclient.Producer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducers", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllProducers")
    @ResponseWrapper(localName = "getAllProducersResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllProducersResponse")
    public List<Producer> getAllProducers();

}
