
package com.gmail.at.sichyuriyy.lab7.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProducerServiceImplService", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", wsdlLocation = "http://localhost:8081/Lab7-0.0.1-SNAPSHOT/ProducerServiceImpl?wsdl")
public class ProducerServiceImplService
    extends Service
{

    private final static URL PRODUCERSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCERSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName PRODUCERSERVICEIMPLSERVICE_QNAME = new QName("http://wsserver.lab7.sichyuriyy.at.gmail.com/", "ProducerServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/Lab7-0.0.1-SNAPSHOT/ProducerServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        PRODUCERSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ProducerServiceImplService() {
        super(__getWsdlLocation(), PRODUCERSERVICEIMPLSERVICE_QNAME);
    }

    public ProducerServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCERSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProducerServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCERSERVICEIMPLSERVICE_QNAME);
    }

    public ProducerServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCERSERVICEIMPLSERVICE_QNAME, features);
    }

    public ProducerServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProducerServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProducerWS
     */
    @WebEndpoint(name = "ProducerServiceImplPort")
    public ProducerWS getProducerServiceImplPort() {
        return super.getPort(new QName("http://wsserver.lab7.sichyuriyy.at.gmail.com/", "ProducerServiceImplPort"), ProducerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProducerWS
     */
    @WebEndpoint(name = "ProducerServiceImplPort")
    public ProducerWS getProducerServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsserver.lab7.sichyuriyy.at.gmail.com/", "ProducerServiceImplPort"), ProducerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCERSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw PRODUCERSERVICEIMPLSERVICE_EXCEPTION;
        }
        return PRODUCERSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
