
package com.gmail.at.sichyuriyy.lab7.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WatchListWS", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WatchListWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteWatchList", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteWatchList")
    @ResponseWrapper(localName = "deleteWatchListResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.DeleteWatchListResponse")
    public void deleteWatchList(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.gmail.at.sichyuriyy.lab7.wsclient.WatchList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWatchListById", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetWatchListById")
    @ResponseWrapper(localName = "getWatchListByIdResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetWatchListByIdResponse")
    public WatchList getWatchListById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "create", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.CreateResponse")
    public void create(
        @WebParam(name = "arg0", targetNamespace = "")
        WatchList arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateWatchList", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateWatchList")
    @ResponseWrapper(localName = "updateWatchListResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.UpdateWatchListResponse")
    public void updateWatchList(
        @WebParam(name = "arg0", targetNamespace = "")
        WatchList arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.gmail.at.sichyuriyy.lab7.wsclient.WatchList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllWatchLists", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllWatchLists")
    @ResponseWrapper(localName = "getAllWatchListsResponse", targetNamespace = "http://wsserver.lab7.sichyuriyy.at.gmail.com/", className = "com.gmail.at.sichyuriyy.lab7.wsclient.GetAllWatchListsResponse")
    public List<WatchList> getAllWatchLists();

}
